version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lav_sms_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  app:
    container_name: lav_sms
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.1"
    volumes:
      - .:/var/www/
    ports:
      - "9000:9000"
    working_dir: /var/www/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: mr.gillesashley@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
